services:
  uniclare-client:
    container_name: uniclare-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./backend/app:/app
    command: [ "fastapi", "dev", "app/main.py", "--port", "80" ]
